config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  resources :projects do
    resources :users
  end

  resources :users do
  end

  get 'welcome/index'

  root 'projects#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = GoodDataRailsApp::Application.get_connection.projects
  end

  def show
    @project = GoodDataRailsApp::Application.get_connection.projects(params[:id])

    begin
      @users = @project.users
    rescue Exception => _e
      @users = nil
    end
  end
end

app/controllers/users_controller.rb
require 'gooddata/models/profile'

class UsersController < ApplicationController
  def index
    @params = params
    if params[:project_id]
      @project = GoodDataRailsApp::Application.get_connection.projects(params[:project_id])
      begin
        @users = @project.users
      rescue Exception => _e
        @users = nil
      end
    end
  end

  def show
    @user = GoodData::Profile[params[:id], :client => GoodDataRailsApp::Application.get_connection]
    begin
      @projects = @user.projects
    rescue Exception => e
      @projects = nil
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoodDataRailsApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/index.html.erb
<h1>Projects</h1>

<ul>
  <% @projects.each do |project| %>
      <li><%= link_to(project.title, project_path(:id => project.pid)) %></li>
  <% end %>
</ul>

app/views/projects/show.html.erb
<h1><%= @project.title %></h1>

<div>
  <span>Author: </span><span> <%= link_to "#{@project.author.first_name} #{@project.author.last_name}", user_path(@project.author.obj_id) %></span>
</div>

<div>
  <span>Contributor: </span><span> <%= link_to "#{@project.contributor.first_name} #{@project.contributor.last_name}", user_path(@project.contributor.obj_id) %></span>
</div>

<h2><%= link_to('Users', project_users_path(:project_id => @project.pid)) %></h2>

app/views/users/index.html.erb
<h1>Users</h1>

<% if @users %>
    <ul>
      <% @users.each do |user| %>
          <li><%= link_to(user.title, user_path(:id => user.obj_id)) %> <%= " - #{user.inspect}" if @params[:inspect]%></li>
      <% end %>
    </ul>
<% else %>
    <div>Forbidden</div>
<% end %>

app/views/users/show.html.erb
<h1><%= "#{@user.first_name} #{@user.last_name} - #{@user.login}" %> </h1>
<div><%= @user.email %></div>

<h2>Projects</h2>
<% if @projects %>
    <ul>
    <% @projects.each do |project| %>
      <li><%= link_to(project.title, project_path(:id => project.pid)) %></li>
    <% end %>
    </ul>
<% else %>
    <div>Forbidden</div>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>